### PR TITLE
add skos:related to link URIs buried in description strings

### PR DESCRIPTION
**Pull request by marqh**
I have added skos:related statements to highlight linked resources as semantic links

Please note, I have manually edited files, to illustrate the proposed change.  if these source controlled files are generated by another process or script, then that ought to be considered before accepting this proposal, I am just not sure.

### CODE REVIEW

**Comment by marqh** [comment]
hello @LuisaIckes 

please excuse my lack of understanding, but you suggest that the changes be made inside tables_en but this folder does not include any .ttl files, it only includes csv files.
It is not clear to me how a new column would be added to a csv file that was only used by a subset of entities, or how any changes made in the tables_en folder would then propagate to the tables folder and the ttl files that are suitable for upload

please may you offer some advice for me?

thank you
mark

**Comment by joergklausen** [comment]
Hi all
The Python script for conversion to .ttl should also go onto the GitHub.
Kind regards
Jörg

_______________________
Dr. Jörg Klausen

Federal Department of Home Affairs FDHA
Federal Office of Meteorology and Climatology MeteoSwiss

Operation Center 1 | P.O. Box 257 | CH-8058 Zurich-Airport
Phone: +41 58 460 92 23
joerg.klausen@meteoswiss.ch<mailto:joerg.klausen@meteoswiss.ch> | Mobile: +41 79 702 94 67

All about weather and climate, please visit our website
www.meteoswiss.ch<http://www.meteoschweiz.admin.ch/web/en.html> and MeteoSwiss App<http://www.meteoswiss.admin.ch/home/services-and-publications/beratung-und-service/meteoswiss-app.html>

All about OSCAR/Surface at https://oscar.wmo.int/surface
All about GAWSIS at https://gawsis.meteoswiss.ch

**Comment by marqh** [comment]
please may I ask:
what is the status of:
https://github.com/wmo-im/wmds/tree/master/tables

and all the work that has gone into the creation of this content?

**Comment by marqh** [comment]
> Hi @marqh
> 
> here on Github we work with the tables in .csv format. @kurt-hectic (Timo) is the one who is then transferring the csv tables into the ttl files needed for the Coderegistry using a Python script.
> 
> Luisa

Hi @LuisaIckes @kurt-hectic 

thank you for the update

please may you confirm whether or not the .ttl files uploaded to the test registry and targeted for the  production codes registry are under source control themselves?

thank you
mark

**Comment by kurt-hectic** [comment]
> please may you confirm whether or not the .ttl files uploaded to the test registry and targeted for the production codes registry are under source control themselves?

Hi @marqh ,

the TTL files as such are not source controlled, but the files (CSV) from which they originate are.
We see the TTL files are publishing format only whereas the source files to which source control (issues, branches etc) are applied are in CSV format.
We could in theory generate TTL files for each modification of a CSV file, but doing this would be a) duplication b) practically difficult as not all members can run the script. Github does not support running custom python scripts serverside that could keep them synced.

Thus, we suggest you edit the CSV files in the folder "tables_en" by creating a new branch linked to this issue and then sending us a pull. We will merge the changes into master.

Timo

> 
> thank you
> mark

**Comment by marqh** [comment]
thanks for the update @kurt-hectic 

does this mean that the content and structure within
https://github.com/wmo-im/wmds/tree/master/tables
is considered legacy and is no longer being maintained?

does this also mean that the multi-lingual content is not being maintained 

thank you
mark

**Comment by LuisaIckes** [comment]
@marqh I think Enrico answered everything in his e-mail and we can close this pull request?

**Comment by marqh** [comment]
> I think Enrico answered everything in his e-mail and we can close this pull request?
@LuisaIckes 
I think the email conversation is fairly independent from the intent of this PR

This PR is intended to add a skos:related field with an explicit URI as the object, to enhance linking to external resources.

however, it is not clear to me from the conversations about content maintenance, parsing, and .ttl file creation how best to achieve this

if a new column is added to an existing csv file, how is that new column managed?
how is the column label in the header translated into a predicate URI?
how is the object interprested, such that if it is a URI it is encoded as a URI?

The volume on content change is not vast, so it is fairly simple to re-implement, but until I know the target implementation I cannot deliver this

**Comment by marqh** [comment]
@kurt-hectic 
my initial suggestion would be to add a column to some CSV files, then the information is being managed under source control

if this is to work, the processing should carefully handle empty fields and recognise http URIs.  A skos:related statement should have a URI as an object, not a string nor an empty.  it is better not to have the statement than to have it wrong

what do you think?

**Comment by kurt-hectic** [comment]
> 
> 
> @kurt-hectic
> my initial suggestion would be to add a column to some CSV files, then the information is being managed under source control
> 
> if this is to work, the processing should carefully handle empty fields and recognise http URIs. A skos:related statement should have a URI as an object, not a string nor an empty. it is better not to have the statement than to have it wrong
> 
> what do you think?

@marqh ,

is this something we could possibly do when we publish the tables as stable?

At this stage we would like to get the raw content out and as experimental, as soon as possible.

Finding a good way to represent this in the source files will take some time and also testing the script etc. 

What do you think?
T

**Pull request merged**
