### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by joergklausen**
Links to test version of WMO codes registry included

### CODE REVIEW

**Comment by joergklausen** [comment]
I have merged, corrected and amended the readme.md and commited to https://github.com/wmo-im/wmds/pull/119/commits. This files is now fully consistent with the WMDR schema documentation at https://github.com/wmo-im/wmdr/blob/master/documentation/WMDR_ModelAndSchemaSpecification.docx. Please push to master, which I am not allowed to do.

**Comment by LuisaIckes** [comment]
@joergklausen : it still has the links to test.codes... instead of the new/real ones to codes.... ?
Or where did you commit it? The link points to the "old" versions, there is only one commit in this pull request from 4th of September?

Also it should be merged to development, not master, we are not merging directly to master (?).

**Comment by joergklausen** [comment]
Hi Luisa
The push didn’t work before, but it has worked now … https://github.com/wmo-im/wmds/pull/119/commits/30098bca678c018772dad88bb04194b1a204ed27
Kind regards
Jörg

_______________________
Dr. Jörg Klausen

Federal Department of Home Affairs FDHA
Federal Office of Meteorology and Climatology MeteoSwiss

Operation Center 1 | P.O. Box 257 | CH-8058 Zurich-Airport
Phone: +41 58 460 92 23
joerg.klausen@meteoswiss.ch<mailto:joerg.klausen@meteoswiss.ch> | Mobile: +41 79 702 94 67

All about weather and climate, please visit our website
www.meteoswiss.ch<http://www.meteoschweiz.admin.ch/web/en.html> and MeteoSwiss App<http://www.meteoswiss.admin.ch/home/services-and-publications/beratung-und-service/meteoswiss-app.html>

All about OSCAR/Surface at https://oscar.wmo.int/surface
All about GAWSIS at https://gawsis.meteoswiss.ch

**Comment by LuisaIckes** [comment]
Yes, now it looks good!

**Comment by LuisaIckes** [comment]
Merged into development now!

**Pull request closed without merging**
