### PR TITLE
remove parenthesis for rdfs:label statement objects

### PR DESCRIPTION
**Pull request by marqh**
I have removed parenthesis from rdfs:label statement objects, as I suggest that these are presented due to another publishing system's ordering criteria, rather than key information.

I  observe that 
http://test.wmocodes.info/wmdr/UncertaintyEstimateProcedure
http://test.wmocodes.info/wmdr/WIGOSFunction
also have parenthesis in rdfs:label instances, but I cannot find the contents for these under this respository.  Have I missed these somewhere?

Please note, I have manually edited files, to illustrate the proposed change.  if these source controlled files are generated by another process or script, then that ought to be considered before accepting this proposal, I am just not sure.

### CODE REVIEW

**Comment by LuisaIckes** [comment]
Hi Marc,
Great for helping with that! 

The current tables which are going to the fast track and have to be uploaded on the code registry are the English tables, so the folder tables_en- you were taking the folder tables. That is why you cannot find the tables above in the repository.

And to be consistent with our workflow it would be better to open an issue and then to create a branch with the same number as the issue and apply all the changes there (in this case the branch should be based on the master), which we will then merge into the master. However, pullrequest should also be fine.

**Comment by LuisaIckes** [comment]
Hi @marqh ,
a question to your changes: In understand that brackets in the notation do not work, but why are brackets in the name also a problem? And is it also a problem if the name starts with a bracket? I noticed that you removed these ones (mostly in the name inapplicable and unknown), but there are other names that still contain brackets (they do not start with a bracket though). Besides that I think all the changes are ok, so we can go forward with this pull request.
Luisa

**Comment by marqh** [comment]
> In understand that brackets in the notation do not work, but why are brackets in the name also a problem?

Hello @LuisaIckes @joergklausen 

The removal of brackets from names is aesthetic, not functional.  

The definition of a name `(unknown)` seems odd to me, and would preferably be defined as `unknown`, I suggest.

Within the `wmds/tables_en` folder, I only replaced the strings
* ~~`(other)`~~ with `other`
* ~~`(unknown)`~~ with `unknown`
* ~~`(inapplicable)`~~ `inapplicable`

would it be helpful for me to remove all changes to the `wmds/tables` folder so that this PR is clearer, only including changes to the `wmds/tables_en` folder?

**Comment by joergklausen** [comment]
Hi all
I agree completely with removing the parenthesis around other, unknown and inapplicable, and I believe I have said that before. These parenthesis will only be used in OSCAR/Surface web application to support these elements coming first in alphabetically ordered lists.
Jörg

_______________________
Dr. Jörg Klausen

Federal Department of Home Affairs FDHA
Federal Office of Meteorology and Climatology MeteoSwiss

Operation Center 1 | P.O. Box 257 | CH-8058 Zurich-Airport
Phone: +41 58 460 92 23
joerg.klausen@meteoswiss.ch<mailto:joerg.klausen@meteoswiss.ch> | Mobile: +41 79 702 94 67

All about weather and climate, please visit our website
www.meteoswiss.ch<http://www.meteoschweiz.admin.ch/web/en.html> and MeteoSwiss App<http://www.meteoswiss.admin.ch/home/services-and-publications/beratung-und-service/meteoswiss-app.html>

All about OSCAR/Surface at https://oscar.wmo.int/surface
All about GAWSIS at https://gawsis.meteoswiss.ch

**Comment by LuisaIckes** [comment]
Merged it into master to be published on the coderegistry!

**Pull request merged**
